services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  php:
    restart: unless-stopped
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/app
    expose:
      - "9000"
    networks:
      - app-network
  air-subs:
    restart: unless-stopped
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: air-subs
    volumes:
      - ./src:/var/www/app
    command: ["php", "/var/www/app/artisan", "app:mqtt-subscribe-air"]
    networks:
      - app-network
  soil-subs:
    restart: unless-stopped
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: soil-subs
    volumes:
      - ./src:/var/www/app
    command: ["php", "/var/www/app/artisan", "app:mqtt-subscribe-soil"]
    networks:
      - app-network
  battery-subs:
    restart: unless-stopped
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: battery-subs
    volumes:
      - ./src:/var/www/app
    command: ["php", "/var/www/app/artisan", "app:mqtt-subscribe-battery"]
    networks:
      - app-network
  mosquitto-server:
    image: eclipse-mosquitto
    container_name: mosquitto-server
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config  # Mount custom config file
      - ./mosquitto/data:/mosquitto/data      # Persist data
      - ./mosquitto/log:/mosquitto/log        # Persist logs
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge